use crate::{PreparedScene, RevisionGate};
use kurbo::{Affine, BezPath};
use srng::runtime::{Geometry, Scene, SceneNode};
use std::collections::{BTreeMap, HashMap, HashSet};
use std::f64::consts::PI;

#[derive(Clone, Copy, Debug, PartialEq)]
struct Matrix { a:f64,b:f64,c:f64,d:f64,e:f64,f:f64 }
impl Matrix {
    const ID:Self=Self{a:1.0,b:0.0,c:0.0,d:1.0,e:0.0,f:0.0};
    fn mul(self,r:Self)->Self{Self{a:self.a*r.a+self.c*r.b,b:self.b*r.a+self.d*r.b,c:self.a*r.c+self.c*r.d,d:self.b*r.c+self.d*r.d,e:self.a*r.e+self.c*r.f+self.e,f:self.b*r.e+self.d*r.f+self.f}}
    fn translate(x:f64,y:f64)->Self{Self{e:x,f:y,..Self::ID}}
    fn scale(x:f64,y:f64)->Self{Self{a:x,d:y,..Self::ID}}
    fn rotate(rad:f64)->Self{let(s,c)=rad.sin_cos();Self{a:c,b:s,c:-s,d:c,e:0.0,f:0.0}}
    fn skew(x:f64,y:f64)->Self{Self{a:1.0,b:y.tan(),c:x.tan(),d:1.0,e:0.0,f:0.0}}
    fn point(self,x:f64,y:f64)->(f64,f64){(self.a*x+self.c*y+self.e,self.b*x+self.d*y+self.f)}
    fn affine(self)->Affine{Affine::new([self.a,self.b,self.c,self.d,self.e,self.f])}
    fn max_scale(self)->f64{(self.a.hypot(self.b)).max(self.c.hypot(self.d))}
}

pub fn prepare_scene(scene:&Scene,revision:u64,gate:&RevisionGate)->PreparedScene{
    let mut normalized=scene.clone();
    let parent=parent_map(&normalized);let roots=viewbox_roots(&normalized,&parent);let mut memo=HashMap::new();let mut visiting=HashSet::new();
    let props=normalized.nodes.iter().map(|n|(n.id.clone(),n.properties.clone())).collect::<HashMap<_,_>>();let mut world=HashMap::new();
    for id in normalized.nodes.iter().map(|n|n.id.clone()).collect::<Vec<_>>(){world.insert(id.clone(),world_matrix(&id,&parent,&props,&roots,&mut memo,&mut visiting));}
    let clip_ids=normalized.nodes.iter().filter_map(|n|n.properties.get("clip-units").map(|_|n.id.clone())).collect::<HashSet<_>>();

    for node in &mut normalized.nodes {
        let m=*world.get(&node.id).unwrap_or(&Matrix::ID); preprocess_paint(node,m); preprocess_mask(node,m);
        if node.kind=="text" && !node.properties.contains_key("data"){continue;}
        if node.kind=="group" && node.properties.contains_key("use-data"){
            let x=prop_number(&node.properties,"source-x").unwrap_or(0.0);let y=prop_number(&node.properties,"source-y").unwrap_or(0.0);
            if let Some(data)=node.properties.get("use-data").map(|v|unquote(v)){node.properties.insert("data".into(),quote(&data));if let Some(v)=node.properties.get("use-fill").cloned(){node.properties.insert("fill".into(),v);}if let Some(v)=node.properties.get("use-stroke").cloned(){node.properties.insert("stroke".into(),v);}bake_node_path(node,m.mul(Matrix::translate(x,y)));}
            continue;
        }
        if node.kind=="group" {
            if let Some(href)=node.properties.get("href").map(|v|unquote(v)){if href.starts_with("data:image/"){normalize_image(node,m,&href);continue;}}
        }
        if !clip_ids.contains(&node.id)&&node.kind!="canvas"{bake_node_path(node,m);}
    }
    materialize_target_clips(&mut normalized,&world);
    for r in &mut normalized.references {apply_opacity(&mut r.properties,1.0);if let Some(t)=r.properties.get("transform").map(|v|parse_transform(&unquote(v))){if let Some(data)=r.properties.get("data").map(|v|unquote(v)){if let Some(out)=transform_path(&data,t){r.properties.insert("data".into(),quote(&out));}}}}
    crate::semantic::prepare_scene(&normalized,revision,gate)
}

fn parent_map(scene:&Scene)->HashMap<String,String>{scene.relations.iter().filter(|r|r.active&&r.kind.as_deref()==Some("contains")).map(|r|(r.to.clone(),r.from.clone())).collect()}
fn viewbox_roots(scene:&Scene,parent:&HashMap<String,String>)->HashMap<String,Matrix>{let mut out=HashMap::new();for n in &scene.nodes{if parent.contains_key(&n.id){continue;}let Some(v)=n.properties.get("viewbox").map(|v|unquote(v))else{continue;};if let Some(m)=viewbox_matrix(&v,n.properties.get("preserve-aspect-ratio").map(|v|unquote(v)).as_deref(),scene.viewport.width,scene.viewport.height){out.insert(n.id.clone(),m);}}out}
fn world_matrix(id:&str,parent:&HashMap<String,String>,props:&HashMap<String,BTreeMap<String,String>>,roots:&HashMap<String,Matrix>,memo:&mut HashMap<String,Matrix>,visiting:&mut HashSet<String>)->Matrix{if let Some(m)=memo.get(id){return *m;}if !visiting.insert(id.to_string()){return Matrix::ID;}let local=props.get(id).and_then(|p|p.get("transform")).map(|v|parse_transform(&unquote(v))).unwrap_or(Matrix::ID);let base=if let Some(p)=parent.get(id){world_matrix(p,parent,props,roots,memo,visiting)}else{roots.get(id).copied().unwrap_or(Matrix::ID)};let m=base.mul(local);visiting.remove(id);memo.insert(id.to_string(),m);m}
fn viewbox_matrix(value:&str,preserve:Option<&str>,vw:f64,vh:f64)->Option<Matrix>{let n=value.split(|c:char|c==','||c.is_whitespace()).filter(|s|!s.is_empty()).map(|s|s.parse::<f64>().ok()).collect::<Option<Vec<_>>>()?;if n.len()!=4||n[2]<=0.0||n[3]<=0.0{return None;}let(x,y,w,h)=(n[0],n[1],n[2],n[3]);let sx=vw/w;let sy=vh/h;let p=preserve.unwrap_or("xMidYMid meet");if p.trim()=="none"{return Some(Matrix::translate(-x*sx,-y*sy).mul(Matrix::scale(sx,sy)));}let s=if p.contains("slice"){sx.max(sy)}else{sx.min(sy)};let ex=vw-w*s;let ey=vh-h*s;let ax=if p.contains("xMin"){0.0}else if p.contains("xMax"){ex}else{ex/2.0};let ay=if p.contains("YMin"){0.0}else if p.contains("YMax"){ey}else{ey/2.0};Some(Matrix::translate(ax-x*s,ay-y*s).mul(Matrix::scale(s,s)))}
fn parse_transform(v:&str)->Matrix{let mut out=Matrix::ID;let mut rest=v.trim();while let Some(open)=rest.find('('){let name=rest[..open].trim();let after=&rest[open+1..];let Some(close)=after.find(')')else{break;};let a=after[..close].split(|c:char|c==','||c.is_whitespace()).filter(|s|!s.is_empty()).filter_map(|s|s.parse::<f64>().ok()).collect::<Vec<_>>();let m=match name{"matrix" if a.len()>=6=>Matrix{a:a[0],b:a[1],c:a[2],d:a[3],e:a[4],f:a[5]},"translate" if !a.is_empty()=>Matrix::translate(a[0],*a.get(1).unwrap_or(&0.0)),"scale" if !a.is_empty()=>Matrix::scale(a[0],*a.get(1).unwrap_or(&a[0])),"rotate" if !a.is_empty()=>{let r=Matrix::rotate(a[0]*PI/180.0);if a.len()>=3{Matrix::translate(a[1],a[2]).mul(r).mul(Matrix::translate(-a[1],-a[2]))}else{r}},"skewX" if !a.is_empty()=>Matrix::skew(a[0]*PI/180.0,0.0),"skewY" if !a.is_empty()=>Matrix::skew(0.0,a[0]*PI/180.0),_=>Matrix::ID};out=out.mul(m);rest=&after[close+1..];}out}
fn bake_node_path(node:&mut SceneNode,m:Matrix){let Some(path)=node_path(node)else{return;};if let Some(out)=transform_path(&path,m){node.properties.insert("data".into(),quote(&out));}if let Some(g)=transformed_bbox(&node.geometry,m){node.geometry=g;}node.properties.remove("transform");}
fn node_path(n:&SceneNode)->Option<String>{if let Some(d)=n.properties.get("data").map(|v|unquote(v)){if !d.trim().is_empty(){return Some(d);}}let Geometry{x:Some(x),y:Some(y),width:Some(w),height:Some(h)}=n.geometry else{return None;};match n.kind.as_str(){"rect"|"group"|"shadow"=>Some(format!("M {x} {y} H {} V {} H {x} Z",x+w,y+h)),"circle"|"ellipse"=>{let rx=w/2.0;let ry=h/2.0;let cx=x+rx;let cy=y+ry;Some(format!("M {} {cy} A {rx} {ry} 0 1 0 {} {cy} A {rx} {ry} 0 1 0 {} {cy} Z",cx-rx,cx+rx,cx-rx))},_=>None}}
fn transform_path(data:&str,m:Matrix)->Option<String>{let mut p=BezPath::from_svg(data).ok()?;p.apply_affine(m.affine());Some(p.to_svg())}
fn transformed_bbox(g:&Geometry,m:Matrix)->Option<Geometry>{let(x,y,w,h)=(g.x?,g.y?,g.width?,g.height?);let p=[m.point(x,y),m.point(x+w,y),m.point(x,y+h),m.point(x+w,y+h)];let minx=p.iter().map(|p|p.0).fold(f64::INFINITY,f64::min);let maxx=p.iter().map(|p|p.0).fold(f64::NEG_INFINITY,f64::max);let miny=p.iter().map(|p|p.1).fold(f64::INFINITY,f64::min);let maxy=p.iter().map(|p|p.1).fold(f64::NEG_INFINITY,f64::max);Some(Geometry{x:Some(minx),y:Some(miny),width:Some(maxx-minx),height:Some(maxy-miny)})}

fn preprocess_paint(node:&mut SceneNode,m:Matrix){let opacity=prop_number(&node.properties,"opacity").unwrap_or(1.0).clamp(0.0,1.0);apply_opacity(&mut node.properties,opacity);let kind=node.properties.get("gradient-kind").map(|v|unquote(v));if kind.as_deref()==Some("linear-gradient"){let units=node.properties.get("gradient-units").map(|v|unquote(v)).unwrap_or_else(||"objectBoundingBox".into());let g=&node.geometry;let x=g.x.unwrap_or(0.0);let y=g.y.unwrap_or(0.0);let w=g.width.unwrap_or(1.0);let h=g.height.unwrap_or(1.0);let p=|k:&str,ax:bool,d:&str|resolve_coord(node.properties.get(k).map(|v|unquote(v)).as_deref().unwrap_or(d),&units,if ax{x}else{y},if ax{w}else{h});let a=m.point(p("gradient-x1",true,"0%"),p("gradient-y1",false,"0%"));let b=m.point(p("gradient-x2",true,"100%"),p("gradient-y2",false,"0%"));node.properties.insert("gradient-start".into(),format!("{}px {}px",fmt(a.0),fmt(a.1)));node.properties.insert("gradient-end".into(),format!("{}px {}px",fmt(b.0),fmt(b.1)));node.properties.insert("fill".into(),"linear-gradient".into());}else if kind.as_deref()==Some("radial-gradient"){let units=node.properties.get("gradient-units").map(|v|unquote(v)).unwrap_or_else(||"objectBoundingBox".into());let g=&node.geometry;let x=g.x.unwrap_or(0.0);let y=g.y.unwrap_or(0.0);let w=g.width.unwrap_or(1.0).abs();let h=g.height.unwrap_or(1.0).abs();let p=|k:&str,ax:bool,d:&str|resolve_coord(node.properties.get(k).map(|v|unquote(v)).as_deref().unwrap_or(d),&units,if ax{x}else{y},if ax{w}else{h});let c=m.point(p("gradient-cx",true,"50%"),p("gradient-cy",false,"50%"));let f=m.point(p("gradient-fx",true,"50%"),p("gradient-fy",false,"50%"));let rr=node.properties.get("gradient-r").map(|v|unquote(v)).unwrap_or_else(||"50%".into());let mut r=if let Some(q)=rr.trim().strip_suffix('%').and_then(|v|v.parse::<f64>().ok()){if units=="objectBoundingBox"{w.max(h)*q/100.0}else{q/100.0}}else{rr.trim_end_matches("px").parse().unwrap_or(0.5)};r*=m.max_scale();node.properties.insert("gradient-cx".into(),fmt(c.0));node.properties.insert("gradient-cy".into(),fmt(c.1));node.properties.insert("gradient-fx".into(),fmt(f.0));node.properties.insert("gradient-fy".into(),fmt(f.1));node.properties.insert("gradient-r".into(),fmt(r));node.properties.insert("gradient-units".into(),"userSpaceOnUse".into());node.properties.insert("fill".into(),"radial-gradient".into());}}
fn resolve_coord(raw:&str,units:&str,origin:f64,extent:f64)->f64{let t=raw.trim();if let Some(p)=t.strip_suffix('%').and_then(|v|v.parse::<f64>().ok()){return if units=="objectBoundingBox"{origin+extent*p/100.0}else{p/100.0};}let n=t.trim_end_matches("px").parse::<f64>().unwrap_or(0.0);if units=="objectBoundingBox"{origin+extent*n}else{n}}
fn preprocess_mask(node:&mut SceneNode,m:Matrix){let Some(data)=node.properties.get("mask-data").cloned()else{return;};let mode=node.properties.get("mask-type").map(|v|unquote(v)).unwrap_or_else(||"luminance".into());let units=node.properties.get("mask-content-units").map(|v|unquote(v)).unwrap_or_else(||"userSpaceOnUse".into());let bbox=if units=="objectBoundingBox"{let g=&node.geometry;Matrix::translate(g.x.unwrap_or(0.0),g.y.unwrap_or(0.0)).mul(Matrix::scale(g.width.unwrap_or(1.0),g.height.unwrap_or(1.0)))}else{Matrix::ID};node.properties.insert("mask-data".into(),opacity_records(&data,1.0,mode=="luminance"));let d=unquote(node.properties.get("mask-data").unwrap());node.properties.insert("mask-data".into(),quote(&transform_records(&d,m.mul(bbox))));}
fn opacity_records(v:&str,o:f64,l:bool)->String{let d=unquote(v);quote(&d.lines().filter_map(|line|{let(c,p)=line.split_once('|')?;let c=if l{luminance_alpha(c)}else{with_alpha(c,o).unwrap_or_else(||c.to_string())};Some(format!("{c}|{p}"))}).collect::<Vec<_>>().join("\n"))}
fn transform_records(v:&str,m:Matrix)->String{v.lines().filter_map(|line|{let(c,p)=line.split_once('|')?;transform_path(p,m).map(|p|format!("{c}|{p}"))}).collect::<Vec<_>>().join("\n")}
fn materialize_target_clips(scene:&mut Scene,world:&HashMap<String,Matrix>){let clips=scene.nodes.iter().map(|n|(n.id.clone(),n.clone())).collect::<HashMap<_,_>>();let mut extra=Vec::new();for n in &mut scene.nodes{let Some(cid)=n.properties.get("clip").map(|v|unquote(v))else{continue;};let Some(src)=clips.get(&cid)else{continue;};let units=src.properties.get("clip-units").map(|v|unquote(v)).unwrap_or_else(||"userSpaceOnUse".into());let Some(data)=src.properties.get("data").map(|v|unquote(v))else{continue;};let base=*world.get(&n.id).unwrap_or(&Matrix::ID);let m=if units=="objectBoundingBox"{let g=&n.geometry;Matrix::translate(g.x.unwrap_or(0.0),g.y.unwrap_or(0.0)).mul(Matrix::scale(g.width.unwrap_or(1.0),g.height.unwrap_or(1.0)))}else{base};let Some(path)=transform_path(&data,m)else{continue;};let mut clone=src.clone();clone.id=format!("__clip_{}",n.id);clone.properties.insert("data".into(),quote(&path));clone.properties.remove("clip-units");n.properties.insert("clip".into(),clone.id.clone());extra.push(clone);}scene.nodes.extend(extra);}
fn normalize_image(node:&mut SceneNode,m:Matrix,href:&str){let x=prop_number(&node.properties,"source-x").unwrap_or(0.0);let y=prop_number(&node.properties,"source-y").unwrap_or(0.0);let w=prop_number(&node.properties,"source-width").unwrap_or(0.0);let h=prop_number(&node.properties,"source-height").unwrap_or(0.0);if w<=0.0||h<=0.0{return;}node.properties.insert("image-data".into(),quote(href));node.properties.insert("image-preserve-aspect-ratio".into(),node.properties.get("image-preserve-aspect-ratio").cloned().unwrap_or_else(||quote("xMidYMid meet")));node.geometry=transformed_bbox(&Geometry{x:Some(x),y:Some(y),width:Some(w),height:Some(h)},m).unwrap_or(Geometry{x:Some(x),y:Some(y),width:Some(w),height:Some(h)});node.properties.insert("data".into(),quote(&node_path(node).unwrap_or_else(||format!("M {x} {y} H {} V {} H {x} Z",x+w,y+h))));}
fn apply_opacity(props:&mut BTreeMap<String,String>,base:f64){let fo=base*prop_number(props,"fill-opacity").unwrap_or(1.0);let so=base*prop_number(props,"stroke-opacity").unwrap_or(1.0);if let Some(v)=props.get("fill").cloned(){if let Some(c)=with_alpha(&v,fo){props.insert("fill".into(),c);}}if let Some(v)=props.get("stroke").cloned(){if let Some(c)=with_alpha(&v,so){props.insert("stroke".into(),c);}}if let Some(v)=props.get("gradient-stops").cloned(){props.insert("gradient-stops".into(),opacity_stops(&v,fo));}if let Some(v)=props.get("pattern-data").cloned(){props.insert("pattern-data".into(),opacity_records(&v,fo,false));}props.remove("opacity");props.remove("fill-opacity");props.remove("stroke-opacity");}
fn prop_number(p:&BTreeMap<String,String>,k:&str)->Option<f64>{unquote(p.get(k)?).trim().trim_end_matches("px").parse().ok()}
fn with_alpha(v:&str,o:f64)->Option<String>{let v=unquote(v);let h=v.strip_prefix('#')?;let b=|s:&str|u8::from_str_radix(s,16).ok();let(r,g,bb,a)=match h.len(){3=>(b(&h[0..1].repeat(2))?,b(&h[1..2].repeat(2))?,b(&h[2..3].repeat(2))?,255),4=>(b(&h[0..1].repeat(2))?,b(&h[1..2].repeat(2))?,b(&h[2..3].repeat(2))?,b(&h[3..4].repeat(2))?),6=>(b(&h[0..2])?,b(&h[2..4])?,b(&h[4..6])?,255),8=>(b(&h[0..2])?,b(&h[2..4])?,b(&h[4..6])?,b(&h[6..8])?),_=>return None};Some(format!("#{r:02x}{g:02x}{bb:02x}{:02x}",(f64::from(a)*o.clamp(0.0,1.0)).round()as u8))}
fn luminance_alpha(v:&str)->String{let v=unquote(v);let Some(h)=v.strip_prefix('#')else{return"#ffffff00".into()};let hex=if h.len()==3{format!("{}{}{}{}{}{}",&h[0..1],&h[0..1],&h[1..2],&h[1..2],&h[2..3],&h[2..3])}else{h[..h.len().min(6)].to_string()};if hex.len()<6{return"#ffffff00".into()}let r=u8::from_str_radix(&hex[0..2],16).unwrap_or(0);let g=u8::from_str_radix(&hex[2..4],16).unwrap_or(0);let b=u8::from_str_radix(&hex[4..6],16).unwrap_or(0);let a=(0.2126*f64::from(r)+0.7152*f64::from(g)+0.0722*f64::from(b)).round()as u8;format!("#ffffff{a:02x}")}
fn opacity_stops(v:&str,o:f64)->String{unquote(v).split(',').map(|s|{let mut f=s.split_whitespace();let off=f.next().unwrap_or("0");let c=f.next().unwrap_or("#000000");format!("{off} {}",with_alpha(c,o).unwrap_or_else(||c.to_string()))}).collect::<Vec<_>>().join(", ")}
fn unquote(v:&str)->String{let v=v.trim();let Some(i)=v.strip_prefix('"').and_then(|x|x.strip_suffix('"'))else{return v.to_string()};i.replace("\\n","\n").replace("\\\"","\"").replace("\\\\","\\")}
fn quote(v:&str)->String{format!("\"{}\"",v.replace('\\',"\\\\").replace('"',"\\\"").replace('\n',"\\n"))}
fn fmt(v:f64)->String{if v.fract().abs()<1e-9{format!("{}",v as i64)}else{format!("{v:.6}").trim_end_matches('0').trim_end_matches('.').to_string()}}

#[cfg(test)]mod tests{use super::*;#[test]fn transform_parser_handles_full_svg_list(){let m=parse_transform("translate(10 20) scale(2) rotate(90)");let p=m.point(1.0,0.0);assert!((p.0-10.0).abs()<1e-6);assert!((p.1-22.0).abs()<1e-6);}#[test]fn viewbox_meet_centers_content(){let m=viewbox_matrix("0 0 100 100",Some("xMidYMid meet"),200.0,100.0).unwrap();assert_eq!(m.point(0.0,0.0),(50.0,0.0));}#[test]fn luminance_mask_converts_gray_to_alpha(){assert_eq!(luminance_alpha("#808080"),"#ffffff80");}}
